---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates for Ubuntu
    apt:
      upgrade: yes
      update_cache: true
    when: ansible_distribution == "Ubuntu"
